/** @description Action names */

export const BEGIN_API_CALL = "BEGIN_API_CALL";
export const API_CALL_ERROR = "API_CALL_ERROR";
export const SET_LOADER_STATUS = "SET_LOADER_STATUS";

export const LOAD_AUTHENTICATION_SUCCESS = "LOAD_AUTHENTICATION_SUCCESS";
export const SAVE_USER_dETAILS = "SAVE_USER_dETAILS";

export const SEARCH_EMAIL_SUCCESS = "SEARCH_EMAIL_SUCCESS";
